# Generated by Django 4.2.1 on 2023-05-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('sex', models.CharField(default='M', max_length=2)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('info', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
