# Generated by Django 4.2.1 on 2023-05-12 02:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('food_no', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('food_img', models.ImageField(upload_to='image/')),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='basedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='basedata',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='mesg',
            fields=[
                ('mes_no', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(max_length=255)),
                ('food_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.basedata')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.basedata'),
        ),
    ]
