# Generated by Django 4.2.1 on 2023-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_food_remove_basedata_id_alter_basedata_username_mesg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='adr',
            field=models.CharField(default=' ', max_length=225),
        ),
        migrations.AddField(
            model_name='food',
            name='context',
            field=models.CharField(default='沒有內文喔！', max_length=225),
        ),
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
