# Generated by Django 4.2.1 on 2023-05-29 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_food_adr_food_context_food_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedata',
            name='photo',
            field=models.ImageField(default='image/logo.png', upload_to='image/'),
        ),
        migrations.CreateModel(
            name='love',
            fields=[
                ('love_no', models.AutoField(primary_key=True, serialize=False)),
                ('mes_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.food')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.basedata')),
            ],
        ),
    ]
