# Generated by Django 4.2.1 on 2023-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_basedata_photo_love'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='mes_no',
            new_name='food_no',
        ),
        migrations.AlterField(
            model_name='basedata',
            name='photo',
            field=models.ImageField(default='image/logo.png', upload_to='photo/'),
        ),
    ]
