# Generated by Django 4.2.6 on 2023-11-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_rename_mes_no_love_food_no_alter_basedata_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('search_no', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.CharField(default=' ', max_length=30)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.basedata')),
            ],
        ),
    ]
